name: Деплой на удалённый сервер

# Триггер на пуш и PR в ветку develop
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      # Настройка SSH для доступа к серверу
      - name: Настройка SSH ключа
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Проверка длины ключа (для отладки)
      - name: Проверка SSH_PRIVATE_KEY
        run: |
          echo "Длина секретного ключа: ${#SSH_PRIVATE_KEY}"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Деплой на удалённый сервер
      - name: Деплой на сервер
        run: |
          ssh -o StrictHostKeyChecking=no root@193.168.48.226 << 'EOF'
            cd ~/glonass2216bot

            echo "🛑 Остановка существующего контейнера..."
            docker-compose down

            echo "🛠 Сборка нового образа..."
            docker-compose build --no-cache

            echo "🚀 Запуск нового контейнера..."
            docker-compose up -d

            echo "✅ Деплой завершён!"
          EOF

      # Просмотр последних логов контейнера
      - name: Просмотр последних логов
        run: |
          ssh -o StrictHostKeyChecking=no root@193.168.48.226 << 'EOF'
            echo "📄 Последние логи контейнера:"
            docker logs --tail 50 glonass2216bot
          EOF
